---

sudo: false

dist: trusty

language: php

before_install:
  - sh -c "if [ $TRAVIS_PHP_VERSION != hhvm ]; then echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi"
  - travis_retry composer self-update
  - travis_retry composer global require --no-update hirak/prestissimo:@stable
  - travis_retry composer global update
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - composer install --prefer-source

before_script:
  - mkdir -p build/logs
  - rm -rf app/cache/*/*

script:
  - composer phpunit

after_script:
  - travis_retry composer coveralls

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm
