imports:
    - { resource: security.yml }

framework:
    secret:          bb5b97682484447a819d7d27a0e8931e
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: [ 'twig' ]
    default_locale:  en
    trusted_proxies: ~
    fragments:       ~
    test: ~
    session:
        storage_id:  session.storage.mock_file
    profiler:
        enabled:     false

# Twig Configuration
twig:
    debug:            true
    strict_variables: true

services:
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
            - { name: twig.extension }

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        path:   "%kernel.cache_dir%/.ht.sqlite"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false

authbucket_oauth2:
    driver:                 orm
    user_provider:          security.user.provider.concrete.default
    model:
        access_token:       AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\AccessToken
        authorize:          AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\Authorize
        client:             AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\Client
        code:               AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\Code
        refresh_token:      AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\RefreshToken
        scope:              AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\Scope
        user:               AuthBucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\User
